inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails

AllCops:
  # Rubyバージョン指定
  TargetRubyVersion: 2.5.5
  # 除外
  Exclude:
    - 'config.ru'
    - 'bin/**'
    - 'lib/**'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

# 日本語でのコメントを許可
Style/AsciiComments:
  Enabled: false

# クラスのコメント必須を無視
Style/Documentation:
  Enabled: false

# モジュール名::クラス名の定義を許可
Style/ClassAndModuleChildren:
  Enabled: false

# 文字リテラルのイミュータブル宣言を無視（freezeになるのはRuby3以降）
Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/ClassLength:
  Max: 200

Metrics/BlockLength:
  Max: 150

Metrics/MethodLength:
  Max: 40

Metrics/AbcSize:
  Max: 100